apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: my-springboot
spec:
 replicas: 3
 template:
  metadata:
   labels:
    app: my-springboot
  spec:
    containers:
    - name: my-springboot
      image: 192.168.159.128/springcloud/springboot:v1.0
      ports:
      - containerPort: 8761