###∂Àø⁄∫≈≈‰÷√
server:
  port: 8081
### ˝æ›ø‚≈‰÷√  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password:
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1 FROM DUAL
    time-between-eviction-runs-millis: 300000
    min-evictable-idle-time-millis: 1800000
    driver-class-name: com.mysql.cj.jdbc.Driver
  # ª∫¥Ê≈‰÷√∂¡»°
  cache:
    type: ehcache
    ehcache:
      config: classpath:app2_ehcache.xml